(function(){'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=ba(this);function r(a,b){if(b)a:{var c=ea;a=a.split(".");for(var f=0;f<a.length-1;f++){var d=a[f];if(!(d in c))break a;c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(f+(g||"")+"_"+d++,g)}function c(g,k){this.g=g;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=ea[b[c]];typeof f==="function"&&typeof f.prototype[a]!="function"&&p(f.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ha=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=ia;
function ma(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,c);f&&Object.defineProperty(a,c,f)}else a[c]=b[c];a.F=b.prototype}function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function na(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}r("Reflect.setPrototypeOf",function(a){return a?a:t?function(b,c){try{return t(b,c),!0}catch(f){return!1}}:null});r("Object.setPrototypeOf",function(a){return a||t});function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(h){this.g=(e+=Math.random()+1).toString();if(h){h=v(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function f(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function d(h){if(!w(h,k)){var l=new c;p(h,k,{value:l})}}function g(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(n){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var e=0;b.prototype.set=function(h,l){if(!f(h))throw Error("Invalid WeakMap key");d(h);if(!w(h,k))throw Error("WeakMap key fail: "+h);h[k][this.g]=l;return this};b.prototype.get=function(h){return f(h)&&w(h,k)?h[k][this.g]:void 0};b.prototype.has=function(h){return f(h)&&w(h,
k)&&w(h[k],this.g)};b.prototype.delete=function(h){return f(h)&&w(h,k)&&w(h[k],this.g)?delete h[k][this.g]:!1};return b});
r("Map",function(a){function b(){var e={};return e.j=e.next=e.head=e}function c(e,h){var l=e[1];return fa(function(){if(l){for(;l.head!=e[1];)l=l.j;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function f(e,h){var l=h&&typeof h;l=="object"||l=="function"?g.has(h)?l=g.get(h):(l=""+ ++k,g.set(h,l)):l="p_"+h;var m=e[0][l];if(m&&w(e[0],l))for(e=0;e<m.length;e++){var n=m[e];if(h!==h&&n.key!==n.key||h===n.key)return{id:l,list:m,index:e,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function d(e){this[0]={};this[1]=b();this.size=0;if(e){e=v(e);for(var h;!(h=e.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var e=Object.seal({x:4}),h=new a(v([[e,"s"]]));if(h.get(e)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=e||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var g=new WeakMap;d.prototype.set=function(e,h){e=e===0?0:e;var l=f(this,e);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=h:(l.entry={next:this[1],j:this[1].j,head:this[1],key:e,value:h},l.list.push(l.entry),this[1].j.next=l.entry,this[1].j=l.entry,this.size++);return this};d.prototype.delete=function(e){e=f(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this[0][e.id],e.entry.j.next=e.entry.next,
e.entry.next.j=e.entry.j,e.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].j=b();this.size=0};d.prototype.has=function(e){return!!f(this,e).entry};d.prototype.get=function(e){return(e=f(this,e).entry)&&e.value};d.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};d.prototype.keys=function(){return c(this,function(e){return e.key})};d.prototype.values=function(){return c(this,function(e){return e.value})};d.prototype.forEach=
function(e,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,e.call(h,m[1],m[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var k=0;return d});r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});r("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});r("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});r("Array.prototype.includes",function(a){return a?a:function(b,c){var f=this;f instanceof String&&(f=String(f));var d=f.length;c=c||0;for(c<0&&(c=Math.max(c+d,0));c<d;c++){var g=f[c];if(g===b||Object.is(g,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});r("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var x=this||self;function oa(a){return a};var pa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function qa(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function ra(a){a=a===void 0?document:a;return a.createElement("img")};function ua(a,b,c){var f=!1;f=f===void 0?!1:f;a.google_image_requests||(a.google_image_requests=[]);var d=ra(a.document);if(c){var g=function(){if(c){var k=a.google_image_requests,e=pa(k,d);e>=0&&Array.prototype.splice.call(k,e,1)}typeof d.removeEventListener==="function"&&d.removeEventListener("load",g,!1);typeof d.removeEventListener==="function"&&d.removeEventListener("error",g,!1)};typeof d.addEventListener==="function"&&d.addEventListener("load",g,!1);typeof d.addEventListener==="function"&&
d.addEventListener("error",g,!1)}f&&(d.attributionSrc="");d.src=b;a.google_image_requests.push(d)};function va(a){x.setTimeout(function(){throw a;},0)};var wa={},y=null;var xa,ya=typeof String.prototype.isWellFormed==="function",za=typeof TextEncoder!=="undefined";var Aa=void 0;function Ba(a){a=Error(a);qa(a,"warning");return a}function Ca(a,b){if(a!=null){var c;var f=(c=Aa)!=null?c:Aa={};c=f[a]||0;c>=b||(f[a]=c+1,a=Error(),qa(a,"incident"),va(a))}};var A=typeof Symbol==="function"&&typeof Symbol()==="symbol";function B(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Da=B("jas",void 0,!0),C=B(void 0,"1oa"),Ea=B(void 0,"0ubsb"),Fa=B(void 0,"0actk"),D=B("m_m","D",!0);var Ga={u:{value:0,configurable:!0,writable:!0,enumerable:!1}},Ha=Object.defineProperties,E=A?Da:"u",G,Ia=[];H(Ia,7);G=Object.freeze(Ia);function Ja(a,b){A||E in a||Ha(a,Ga);a[E]|=b}function H(a,b){A||E in a||Ha(a,Ga);a[E]=b};var I={};function J(a,b){return b===void 0?a.g!==K&&!!(2&(a.h[E]|0)):!!(2&b)&&a.g!==K}var K={},Ka=Object.freeze({});function La(a,b,c){var f=b&128?0:-1,d=a.length,g;if(g=!!d)g=a[d-1],g=g!=null&&typeof g==="object"&&g.constructor===Object;var k=d+(g?-1:0);for(b=b&128?1:0;b<k;b++)c(b-f,a[b]);if(g){a=a[d-1];for(var e in a)!isNaN(e)&&c(+e,a[e])}};var Ma=typeof x.BigInt==="function"&&typeof x.BigInt(0)==="bigint";var Na=Number.MIN_SAFE_INTEGER.toString(),Oa=Ma?BigInt(Number.MIN_SAFE_INTEGER):void 0,Pa=Number.MAX_SAFE_INTEGER.toString(),Qa=Ma?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Ra(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var f=a[c],d=b[c];if(f>d)return!1;if(f<d)return!0}};var Sa=0,Ta=0,Ua;var Va=Number.isFinite;function Wa(a){if(!Va(a))throw Ba("enum");return a|0}function Xa(a){if(typeof a!=="number")throw Ba("int32");if(!Va(a))throw Ba("int32");return a|0}function Ya(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return Va(a)?a|0:void 0}function M(a){if(a!=null&&typeof a!=="string")throw Error();return a};function Za(a){return a};function $a(a,b,c,f){var d=f!==void 0;f=!!f;var g=[],k=a.length,e=4294967295,h=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=k&&a[k-1];n!=null&&typeof n==="object"&&n.constructor===Object?(k--,e=k):n=void 0;if(l&&!(b&128)&&!d){h=!0;var q;e=((q=ab)!=null?q:Za)(e-m,m,a,n)+m}}b=void 0;for(d=0;d<k;d++)if(q=a[d],q!=null&&(q=c(q,f))!=null)if(l&&d>=e){var L=d-m,F=void 0;((F=b)!=null?F:b={})[L]=q}else g[d]=q;if(n)for(var z in n)a=n[z],a!=null&&(a=c(a,f))!=null&&(k=+z,d=void 0,l&&!Number.isNaN(k)&&
(d=k+m)<e?g[d]=a:(k=void 0,((k=b)!=null?k:b={})[z]=a));b&&(h?g.push(b):g[e]=b);return g}function bb(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ma?a>=Oa&&a<=Qa:a[0]==="-"?Ra(a,Na):Ra(a,Pa))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[E]|0;return a.length===0&&b&1?void 0:$a(a,b,bb)}if(a!=null&&a[D]===I)return cb(a);return}return a}var ab;function cb(a){a=a.h;return $a(a,a[E]|0,bb)};var db,eb;function fb(a){switch(typeof a){case "boolean":return db||(db=[0,void 0,!0]);case "number":return a>0?void 0:a===0?eb||(eb=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}
function N(a,b,c,f){f=f===void 0?0:f;if(a==null){var d=32;c?(a=[c],d|=128):a=[];b&&(d=d&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");d=a[E]|0;2048&d&&!(2&d)&&gb();if(d&256)throw Error("farr");if(d&64)return f!==0||d&2048||H(a,d|2048),a;if(c&&(d|=128,c!==a[0]))throw Error("mid");a:{c=a;d|=64;var g=c.length;if(g){var k=g-1,e=c[k];if(e!=null&&typeof e==="object"&&e.constructor===Object){b=d&128?0:-1;k-=b;if(k>=1024)throw Error("pvtlmt");for(var h in e)g=+h,g<k&&(c[g+b]=e[h],delete e[h]);
d=d&-8380417|(k&1023)<<13;break a}}if(b){h=Math.max(b,g-(d&128?0:-1));if(h>1024)throw Error("spvt");d=d&-8380417|(h&1023)<<13}}}d|=64;f===0&&(d|=2048);H(a,d);return a}function gb(){Ca(Fa,5)};function hb(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[E]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=O(a,c,!1,b&&!(c&16)):(Ja(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[D]===I)return b=a.h,c=b[E]|0,J(a,c)?a:jb(a,b,c)?kb(a,b):O(b,c)}function kb(a,b,c){a=new a.constructor(b);c&&(a.g=K);a.l=K;return a}function O(a,b,c,f){f!=null||(f=!!(34&b));a=$a(a,b,hb,f);f=32;c&&(f|=2);b=b&8380609|f;H(a,b);return a}
function lb(a){if(a.g!==K)return!1;var b=a.h;b=O(b,b[E]|0);Ja(b,2048);a.h=b;a.g=void 0;a.l=void 0;return!0}function mb(a){if(!lb(a)&&J(a,a.h[E]|0))throw Error();}function nb(a,b){b===void 0&&(b=a[E]|0);b&32&&!(b&4096)&&H(a,b|4096)}function jb(a,b,c){return c&2?!0:c&32&&!(c&4096)?(H(b,c|2),a.g=K,!0):!1};function ob(a,b){if(b===-1)return null;var c=b+-1,f=a.length-1;if(!(f<0)){if(c>=f)if(a=a[f],a!=null&&typeof a==="object"&&a.constructor===Object)b=a[b];else if(c===f)b=a;else return;else b=a[c];return b}}function pb(a,b,c){mb(a);a=a.h;P(a,a[E]|0,b,c)}
function P(a,b,c,f){var d=c+-1,g=a.length-1;if(g>=0&&d>=g){var k=a[g];if(k!=null&&typeof k==="object"&&k.constructor===Object)return k[c]=f,b}if(d<=g)return a[d]=f,b;if(f!==void 0){var e;g=((e=b)!=null?e:b=a[E]|0)>>13&1023||536870912;c>=g?f!=null&&(d={},a[g+-1]=(d[c]=f,d)):a[d]=f}return b}function Q(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function R(a,b,c,f){mb(a);a=a.h;var d=a[E]|0;if(f==null){var g=qb(a);if(rb(g,a,d,c)===b)g.set(c,0);else return}else{g=qb(a);var k=rb(g,a,d,c);k!==b&&(k&&(d=P(a,d,k)),g.set(c,b))}P(a,d,b,f)}function qb(a){if(A){var b;return(b=a[C])!=null?b:a[C]=new Map}if(C in a)return a[C];b=new Map;Object.defineProperty(a,C,{value:b});return b}function rb(a,b,c,f){var d=a.get(f);if(d!=null)return d;for(var g=d=0;g<f.length;g++){var k=f[g];ob(b,k)!=null&&(d!==0&&(c=P(b,c,d)),d=k)}a.set(f,d);return d}
function sb(a,b,c,f,d,g,k,e){var h=J(a,c);g=h?1:g;k=!!k||g===3;h=e&&!h;(g===2||h)&&lb(a)&&(b=a.h,c=b[E]|0);a=ob(b,d);e=Array.isArray(a)?a:G;var l=e===G?7:e[E]|0;a=l;2&c&&(a|=2);var m=a|1;if(a=!(4&m)){var n=e,q=c,L=!!(2&m);L&&(q|=2);for(var F=!L,z=!0,ca=0,sa=0;ca<n.length;ca++){var u=n[ca];var da=f;if(u==null||u[D]!==I)if(Array.isArray(u)){var ib=u[E]|0;var ta=ib|q&32;ta|=q&2;ta!==ib&&H(u,ta);u=new da(u)}else u=void 0;u instanceof f&&(L||(da=J(u),F&&(F=!da),z&&(z=da)),n[sa++]=u)}sa<ca&&(n.length=sa);
m|=4;m=z?m&-4097:m|4096;m=F?m|8:m&-9}m!==l&&(H(e,m),2&m&&Object.freeze(e));if(h&&!(8&m||!e.length&&(g===1||(g!==4?0:2&m||!(16&m)&&32&c)))){Q(m)&&(e=Array.prototype.slice.call(e),m=tb(m,c),c=P(b,c,d,e));f=e;h=m;for(l=0;l<f.length;l++)n=f[l],m=n.h,q=m[E]|0,m=J(n,q)?jb(n,m,q)?kb(n,m,!0):new n.constructor(O(m,q,!1)):n,n!==m&&(f[l]=m);h|=8;m=h=f.length?h|4096:h&-4097;H(e,m)}h=f=m;g===1||(g!==4?0:2&f||!(16&f)&&32&c)?Q(f)||(f|=!e.length||a&&!(4096&f)||32&c&&!(4096&f||16&f)?2:256,f!==h&&H(e,f),Object.freeze(e)):
(g===2&&Q(f)&&(e=Array.prototype.slice.call(e),h=0,f=tb(f,c),c=P(b,c,d,e)),Q(f)||(k||(f|=16),f!==h&&H(e,f)));2&f||!(4096&f||16&f)||nb(b,c);return e}function ub(a,b){var c=a.h;return sb(a,c,c[E]|0,vb,b,void 0===Ka?2:4,!1,!0)}
function wb(a,b,c){mb(a);var f=a.h,d=f[E]|0;if(c==null)return P(f,d,b),a;for(var g=c===G?7:c[E]|0,k=g,e=Q(g),h=e||Object.isFrozen(c),l=!0,m=!0,n=0;n<c.length;n++){var q=c[n];e||(q=J(q),l&&(l=!q),m&&(m=q))}e||(g=l?13:5,g=m?g&-4097:g|4096);h&&g===k||(c=Array.prototype.slice.call(c),k=0,g=tb(g,d));g!==k&&H(c,g);d=P(f,d,b,c);2&g||!(4096&g||16&g)||nb(f,d);return a}function tb(a,b){return a=(2&b?a|2:a&-3)&-273};function xb(){this.g=[]}xb.prototype.length=function(){return this.g.length};xb.prototype.end=function(){var a=this.g;this.g=[];return a};function S(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function yb(a,b){if(b>=0)S(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function zb(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function Ab(){this.l=[];this.i=0;this.g=new xb}function Bb(a,b){b.length!==0&&(a.l.push(b),a.i+=b.length)}function Cb(a,b){S(a.g,b*8+2);b=a.g.end();Bb(a,b);b.push(a.i);return b}function Db(a,b){var c=b.pop();for(c=a.i+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.i++;b.push(c);a.i++};function T(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var Eb=T(),Fb=T(),Gb=T(),Hb=T(),Ib=T();function U(a,b,c){this.h=N(a,b,c)}U.prototype.toJSON=function(){var a=cb(this);return a};U.prototype[D]=I;U.prototype.toString=function(){return this.h.toString()};function V(a,b){this.g=a;a=oa(Eb);this.i=!!a&&b===a||!1}function Jb(){var a=Kb;var b=b===void 0?Eb:b;return new V(a,b)}function Kb(a,b,c,f,d){b=Lb(b,f);b!=null&&(c=Cb(a,c),d(b,a),Db(a,c))}var Mb=Jb(),Nb=Jb(),Ob=Symbol(),Pb=Symbol(),Qb,Rb;
function Sb(a){var b=Tb,c=Ub,f=a[Ob];if(f)return f;f={};f.C=a;f.m=fb(a[0]);var d=a[1],g=1;d&&d.constructor===Object&&(f.o=d,d=a[++g],typeof d==="function"&&(f.v=!0,Qb!=null||(Qb=d),Rb!=null||(Rb=a[g+1]),d=a[g+=2]));for(var k={};d&&Array.isArray(d)&&d.length&&typeof d[0]==="number"&&d[0]>0;){for(var e=0;e<d.length;e++)k[d[e]]=d;d=a[++g]}for(e=1;d!==void 0;){typeof d==="number"&&(e+=d,d=a[++g]);var h=void 0;if(d instanceof V)var l=d;else l=Mb,g--;d=void 0;if((d=l)==null?0:d.i){d=a[++g];h=a;var m=g;
typeof d==="function"&&(d=d(),h[m]=d);h=d}d=a[++g];m=e+1;typeof d==="number"&&d<0&&(m-=d,d=a[++g]);for(;e<m;e++){var n=k[e];h?c(f,e,l,h,n):b(f,e,l,n)}}return a[Ob]=f}function Lb(a,b){if(a instanceof U)return a.h;if(Array.isArray(a))return N(a,b[0],b[1],2)};function Tb(a,b,c){a[b]=c.g}function Ub(a,b,c,f){var d,g,k=c.g;a[b]=function(e,h,l){return k(e,h,l,g||(g=Sb(f).m),d||(d=Vb(f)))}}function Vb(a){var b=a[Pb];if(!b){var c=Sb(a);b=function(f,d){return Wb(f,d,c)};a[Pb]=b}return b}function Wb(a,b,c){La(a,a[E]|0,function(f,d){if(d!=null){var g=Xb(c,f);g?g(b,d,f):f<500||Ca(Ea,3)}})}
function Xb(a,b){var c=a[b];if(c)return c;if(c=a.o)if(c=c[b]){c=Array.isArray(c)?c[0]instanceof V?c:[Nb,c]:[c,void 0];var f=c[0].g;if(c=c[1]){var d=Vb(c),g=Sb(c).m;c=a.v?Rb(g,d):function(k,e,h){return f(k,e,h,g,d)}}else c=f;return a[b]=c}};function W(a,b){return new V(a,b)}
function Yb(a,b,c){b=b==null||typeof b==="string"?b:void 0;if(b!=null){var f=!1;f=f===void 0?!1:f;if(za){if(f&&(ya?!b.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b)))throw Error("Found an unpaired surrogate");b=(xa||(xa=new TextEncoder)).encode(b)}else{for(var d=0,g=new Uint8Array(3*b.length),k=0;k<b.length;k++){var e=b.charCodeAt(k);if(e<128)g[d++]=e;else{if(e<2048)g[d++]=e>>6|192;else{if(e>=55296&&e<=57343){if(e<=56319&&k<b.length){var h=b.charCodeAt(++k);
if(h>=56320&&h<=57343){e=(e-55296)*1024+h-56320+65536;g[d++]=e>>18|240;g[d++]=e>>12&63|128;g[d++]=e>>6&63|128;g[d++]=e&63|128;continue}else k--}if(f)throw Error("Found an unpaired surrogate");e=65533}g[d++]=e>>12|224;g[d++]=e>>6&63|128}g[d++]=e&63|128}}b=d===g.length?g:g.subarray(0,d)}S(a.g,c*8+2);S(a.g,b.length);Bb(a,a.g.end());Bb(a,b)}}
var Zb=W(function(a,b,c){b=b==null||typeof b==="number"?b:b==="NaN"||b==="Infinity"||b==="-Infinity"?Number(b):void 0;b!=null&&(S(a.g,c*8+1),a=a.g,c=Ua||(Ua=new DataView(new ArrayBuffer(8))),c.setFloat64(0,+b,!0),Sa=c.getUint32(0,!0),Ta=c.getUint32(4,!0),zb(a,Sa),zb(a,Ta))},Hb),$b=W(function(a,b,c){b=Ya(b);b!=null&&b!=null&&(S(a.g,c*8),yb(a.g,b))},Gb),ac=W(Yb,Fb),bc=W(Yb,Fb),cc,dc=void 0;dc=dc===void 0?Eb:dc;
cc=new V(function(a,b,c,f,d){if(Array.isArray(b))for(var g=0;g<b.length;g++){var k=a,e=c,h=d,l=Lb(b[g],f);l!=null&&(e=Cb(k,e),h(l,k),Db(k,e))}},dc);var ec=W(function(a,b,c){b=Ya(b);b!=null&&(b=parseInt(b,10),S(a.g,c*8),yb(a.g,b))},Ib);function vb(a){this.h=N(a)}ma(vb,U);var fc=[1,2,3],hc=[4,5];var ic=[0,fc,hc,ec,-1,bc,Zb,bc,$b];function jc(a){this.h=N(a)}ma(jc,U);jc.prototype.i=function(a){return function(){var b=new Ab;Wb(this.h,b,Sb(a));Bb(b,b.g.end());for(var c=new Uint8Array(b.i),f=b.l,d=f.length,g=0,k=0;k<d;k++){var e=f[k];c.set(e,g);g+=e.length}b.l=[c];return c}}([0,cc,ic,ac,1,ac,$b]);function kc(a){this.h=N(a)}ma(kc,U);kc.prototype.setData=function(a,b){var c=vb;mb(this);var f=this.h;c=sb(this,f,f[E]|0,c,2,2,!0);if(typeof a!=="number"||a<0||a>c.length)throw Error();a!=void 0?c.splice(a,1,b):c.push(b);var d=a=c===G?7:c[E]|0;(b=J(b))?(a&=-9,c.length===1&&(a&=-4097)):a|=4096;a!==d&&H(c,a);b||nb(f);return this};function lc(){this.data=[];this.i=[];this.g=[]}lc.prototype.setData=function(a,b,c){this.g.includes(c)&&this.data.push({key:a,value:b,channel:c})};function mc(a){return a.data.some(function(b){return b.channel===1})}lc.prototype.setAttribute=function(a,b){this.i.push({key:a,value:b})};
function nc(a,b,c,f){var d=new vb;typeof a==="string"?R(d,3,fc,M(a)):f?R(d,1,fc,a==null?a:Wa(a)):R(d,2,fc,a==null?a:Wa(a));if(typeof b==="number"){if(b==null)a=b;else{if(typeof b!=="number")throw Error("Value of float/double field must be a number, found "+typeof b+": "+b);a=b}R(d,4,hc,a)}else R(d,5,hc,M(b));c&&pb(d,6,c==null?c:Xa(c));return d};function X(){this.g=new lc;this.l=Date.now()}
X.prototype.init=function(a,b,c,f,d,g){var k=this;this.g.g.push.apply(this.g.g,b instanceof Array?b:na(v(b)));this.B=a;this.i=d;this.A=c;if(f)for(a=v(f),b=a.next();!b.done;b=a.next())c=v(b.value),b=c.next().value,c=c.next().value,this.g.setAttribute(b,c);if(g){g=v(g);for(a=g.next();!a.done;a=g.next())c=v(a.value),a=c.next().value,b=c.next().value,c=c.next().value,this.setData(a,b,c);document.readyState==="complete"?this.send():window.addEventListener("load",function(){k.send()})}};
X.prototype.getBaseTime=function(){return this.l};X.prototype.setData=function(a,b,c){this.g.setData(a,b,c)};X.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};X.prototype.send=function(a){var b=this,c=mc(this.g)?0:100;a=a!=null?a:c;a>0?setTimeout(function(){return void oc(b)},a):oc(this)};
function oc(a){if(a.g.data.length>0){var b=a.B,c=a.i,f=a.A,d=a.g,g=[];var k=v(d.i);for(var e=k.next();!e.done;e=k.next())e=e.value,g.push(nc(e.key,e.value,void 0,!0));k=[];d=v(d.data);for(e=d.next();!e.done;e=d.next())e=e.value,k.push(nc(e.key,e.value,e.channel,!1));d=new kc;g=wb(d,1,g);k=wb(g,2,k);g=new jc;k=ub(k,1).concat(ub(k,2));g=wb(g,1,k);b&&pb(g,2,M(b));f&&pb(g,4,M(f));c&&pb(g,5,c==null?c:Xa(c));b=g.i();var h;h===void 0&&(h=0);if(!y)for(y={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),
f=["+/=","+/","-_=","-_.","-_"],g=0;g<5;g++)for(k=c.concat(f[g].split("")),wa[g]=k,d=0;d<k.length;d++)e=k[d],y[e]===void 0&&(y[e]=d);h=wa[h];c=Array(Math.floor(b.length/3));f=h[64]||"";for(g=k=0;k<b.length-2;k+=3){var l=b[k],m=b[k+1];e=b[k+2];d=h[l>>2];l=h[(l&3)<<4|m>>4];m=h[(m&15)<<2|e>>6];e=h[e&63];c[g++]=d+l+m+e}d=0;e=f;switch(b.length-k){case 2:d=b[k+1],e=h[(d&15)<<2]||f;case 1:b=b[k],c[g]=h[b>>2]+h[(b&3)<<4|d>>4]+e+f}h="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+c.join("").replace(/\//g,
"_").replace(/\+/g,"-");b=window;var n=n===void 0?!1:n;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&typeof b.navigator.sendBeacon==="function"?b.navigator.sendBeacon(h):ua(b,h,n===void 0?!1:n);a.g.data=[]}}if(!window.mys||!window.mys.pingback)for(var pc=new X,qc=["mys","pingback"],Y=x,Z;qc.length&&(Z=qc.shift());)qc.length||pc===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=pc;}).call(this);
